spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 1488
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.khorunzhev.otus.homework2.changelog

logging:
  level:
    ROOT: INFO