DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, FULLNAME VARCHAR(255));
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(255));

CREATE TABLE BOOK(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    CONSTRAINT FK_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID));
